### PR TITLE
Fix blink priority in cli wallet

### LINKED ISSUE #1165: Blink Bug V.7.1.9 In LOKI CORE
**blink transfer not defaulting in latest v7.1.9**

When typing **Transfer Address Amount** to send a blink transaction in the Cli wallet even though its set priority 0  it does not send blink and the fee remains 0.04. The expected behavior is to default to BLINK without specification.

image

When typing  **Transfer Blink Address Amount** to send a blink transaction it goes through properly and has the blink fee of 0.1 

When sending with the default **Transfer Address Amount** to Tradeogre I takes about 10 blocks before tradeable. By manually specifiying **Transfer Blink Address Amount** the loki was avaiable within 15 seconds and tradeable. 

image

Unsure what revision of the wallet the bug started.

### PR DESCRIPTION
**Pull request by jagerman**
simplewallet needs to recognize 0 (for both unspecified and default priority) as meaning blink for blinkable transactions.

Fixes #1165

### CODE REVIEW

File: src/simplewallet/simplewallet.cpp [hunk 1]
```diff
@@ -5550,6 +5550,13 @@ bool simple_wallet::transfer_main(Transfer transfer_type, const std::vector<std:
   std::set<uint32_t> subaddr_indices  = {};
   if (!parse_subaddr_indices_and_priority(*m_wallet, local_args, subaddr_indices, priority)) return false;
 
+  if (priority == 0)
+  {
+    priority = m_wallet->get_default_priority();
+    if (priority == 0)
+      priority = transfer_type == Transfer::Locked ? tools::tx_priority_unimportant : tools::tx_priority_blink;
```
Comment (Doy-lee) [inline src/simplewallet/simplewallet.cpp:5557]: This prevents users using blink to guarantee a locked transfer will get onto the blockchain, that feels slightly wrong to be removing that option.

Comment (jagerman) [reply src/simplewallet/simplewallet.cpp:5557]: Just below this is a line that bails with an error if priority is set to blink for a locked transfer.

(I don't know why we impose that and agree it should go if there isn't a compelling reason, but needs to be separate from this PR).
